spring.datasource.jndi-name=java:/jdbc/client_api
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
app.default-user.name=${DEFAULT_ADMIN_NAME:Administrador}
app.default-user.email=${DEFAULT_ADMIN_EMAIL:admin@admin.com}
app.default-user.password=${DEFAULT_ADMIN_PASSWORD:}
app.default-user.document=${DEFAULT_ADMIN_DOCUMENT:00000000000}
app.default-user.phone=${DEFAULT_ADMIN_PHONE:00000000000}
